[book]
title = "Rust 参考手册开发者指南"
language = "zh"
authors = ["The Rust Project Developers", "Felix (https://github.com/git-push-felix)"]

[output.html]
git-repository-url = "https://github.com/git-push-felix/reference-zh/"
# edit-url-template = "https://github.com/git-push-felix/reference-zh/edit/main/dev-guide/{path}"
smart-punctuation = true

[output.html.search]
use-boolean-and = true
